name: OlivoApp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # Librerías para seguridad y datos
  flutter_dotenv: ^5.1.0
  mongo_dart: ^0.10.0
  intl: ^0.20.2
  http: ^1.1.0
  # IA y almacenamiento local
  google_generative_ai: any
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  hive_generator: ^2.0.1

# Configuración de iconos (Nivel raíz)
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  # Los assets SIEMPRE van aquí, con dos espacios de sangría respecto a flutter
  assets:
    - .env
    - assets/icon/